FROM ubuntu:latest 

ARG WORKING_DIR=/app
ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
WORKDIR ${WORKING_DIR}
COPY ${GITHUB_WORKSPACE} /app

RUN apt update && apt upgrade -y \
    python3-pip && apt-get install -y python3.6 wget unzip curl && \
    pip3 install -r requirements.txt && \
    apt autoremove -y

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt -y update
RUN apt install -y google-chrome-stable

# install chromedriver
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

CMD ["python3", "store-scrape/find_stores.py"]